version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
